FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnetsdk 
WORKDIR /src

COPY ./WebAPI.sln .
COPY ./JokeAPI/JokeAPI.csproj ./JokeAPI/
COPY ./JokeAPITests/JokeAPITests.csproj ./JokeAPITests/
RUN ["dotnet", "restore"]
COPY . .

FROM dotnetsdk AS test
ENTRYPOINT ["dotnet", "test"]

## build image for WebAPI with both API and Test - image name webapithird - image size 242MB
#FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnetsdk 
#WORKDIR /src

#COPY ./WebAPI.sln .
#COPY ./JokeAPI/JokeAPI.csproj ./JokeAPI/
#COPY ./JokeAPITests/JokeAPITests.csproj ./JokeAPITests/
#COPY . .
#RUN dotnet publish -c Release -o output

#FROM mcr.microsoft.com/dotnet/aspnet:6.0
#WORKDIR /app
#COPY --from=dotnetsdk /src/output .
#EXPOSE 80
#ENTRYPOINT ["dotnet", "JokeAPI.dll"]



