version: "3.8"
services:
  unit-tests:
    build: 
      context: .
      dockerfile: ./Dockerfile.buildandtest
      target: test
    
  publish:
    image: docker.myob.com/future-makers-academy/imay-webapi:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile.buildandtest
    ports: 
      - "7149:80"
    
  
  


