#Original - image size 1.04GB
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnetsdk 
WORKDIR /src

COPY ./WebAPI.sln .
COPY ./JokeAPI/JokeAPI.csproj ./JokeAPI/
COPY ./JokeAPITests/JokeAPITests.csproj ./JokeAPITests/
RUN ["dotnet", "restore"]
COPY . .

FROM dotnetsdk AS test
ENTRYPOINT ["dotnet", "test"]


#Option 2 - image size 1.09GB
#FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dotnetsdk 
#WORKDIR /src

#COPY ./WebAPI.sln .
#COPY JokeAPI/JokeAPI.csproj ./JokeAPI/
#RUN dotnet restore JokeAPI/JokeAPI.csproj
#COPY ./JokeAPI/. ./JokeAPI/
#RUN dotnet publish JokeAPI -c Release -o output --no-restore /restore

#FROM dotnetsdk
#WORKDIR /test
#COPY JokeAPITests/JokeAPITests.csproj ./JokeAPITests/
#RUN dotnet restore JokeAPITests/JokeAPITests.csproj
#COPY ./JokeAPITests/. ./JokeAPITests/
#COPY --from=dotnetsdk /src .
#EXPOSE 80
#ENTRYPOINT ["dotnet", "test"]


